### ISSUE TITLE
[유저] 장바구니 Read

### ISSUE THREAD

**Issue by vemm8ks2** [vemm8ks2/WEB-JSP#245]

**Comment by hsheeh** [comment]
![image](https://github.com/user-attachments/assets/3ab56d41-8ecc-4f59-8889-6af3f10299c1)

유저 장바구니를 눌렀을떄 보일만한 것들?
상품이미지 상품명 상품개수 상품단가 상품합계(개수*단가) 삭제버튼
결제버튼 총금액(모든 상품 합계를 더한 값)

그러려면 필요한것
cart에서 유저의 장바구니, 상품개수 
product에서 상품이미지 상품명 상품가격 

여기서 문제.. 테이블이 다른데 어떻게 같이 가져오지..?
